---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xlp.
--- DateTime: 2019/1/23 23:25
---
-- 1.两个减号是单行注释
--[[
2.多行注释
]]

print("hello world!")
-- 在对一个字符串数字进行算术操作时，会将其转换为数字
print("2"+8)
-- 字符串连接使用..
print("123".."456")
-- 计算字符串长度使用#号
print(#"my name is xiaoming.")

print("==================================Lua变量=======================================")
-- 全局变量
-- 局部变量
-- 表中的域

a = 10 -- 全局变量
local b = 10 -- 局部变量
a = "hello".." world!"
a,b = 1,2
-- 交换变量，会先计算右边所有的值，再进行赋值操作
a,b = b,a


--[[流程控制]]
print("==================================流程控制=======================================")
if (0) then
   print("0为true")
end

print("==================================Lua函数=======================================")
function max(num1,num2)
   if num1 > num2 then
      return num1
   else
      return num2
   end
end
-- 多返回值
print(max(100,2))

-- 可变参数


require "luasql.mysql"

env = luasql.mysql()
print(env)
conn = env:connect("third-eye","root","6550d276f2ef3748","192.168.1.193",3306)
conn:execute"SET NAMES UTF8"
print(conn)
cur = conn:execute("SELECT * FROM organization");
row = cur:fetch({},"A")
while row do
   print(row.id)
   row = cur:fetch({},"A")
end
conn.close()